import {
  BookCheck,
  FileEdit,
  Globe,
  Headphones,
  LayoutGrid,
  Megaphone,
  Palette,
  PenLine,
  Rocket,
  Tablet,
} from "lucide-react";

export const services = [
  {
    slug: "ghostwriting",
    title: "Ghostwriting",
    shortDescription: "Transform your ideas into compelling narratives with our professional ghostwriting services.",
    icon: PenLine,
    image: "/images/services/ghostwriting.jpg",
    heroDescription: "Have a story to tell but struggle to put it into words? Our experienced ghostwriters bring your vision to life while preserving your unique voice.",
    features: [
      "Dedicated professional ghostwriter matched to your genre",
      "Complete confidentiality and NDA protection",
      "Regular progress updates and revision rounds",
      "Your voice, your story, professionally crafted",
      "Research and interview sessions included",
      "Final manuscript in your preferred format",
    ],
    process: [
      { step: 1, title: "Discovery Call", description: "We discuss your vision, goals, and expectations for the book." },
      { step: 2, title: "Outline Development", description: "Create a detailed chapter-by-chapter outline for approval." },
      { step: 3, title: "Writing Phase", description: "Our ghostwriter crafts your manuscript with regular check-ins." },
      { step: 4, title: "Revisions", description: "Multiple revision rounds to perfect your book." },
      { step: 5, title: "Final Delivery", description: "Receive your polished manuscript ready for publishing." },
    ],
    faqs: [
      { question: "Will the book be in my name?", answer: "Absolutely! You retain full authorship and credit. Our ghostwriters work behind the scenes." },
      { question: "How involved will I be in the process?", answer: "As involved as you want! From minimal input to active collaboration, we adapt to your preference." },
      { question: "How long does ghostwriting take?", answer: "Typically 3-6 months depending on book length and complexity." },
    ],
  },
  {
    slug: "book-editing",
    title: "Book Editing",
    shortDescription: "Polish your manuscript to perfection with our comprehensive editing services.",
    icon: FileEdit,
    image: "/images/services/editing.jpg",
    heroDescription: "Every great book deserves meticulous editing. Our editors refine your manuscript while honoring your creative vision.",
    features: [
      "Developmental editing for structure and flow",
      "Line editing for style and clarity",
      "Copy editing for grammar and consistency",
      "Genre-specific editors with industry experience",
      "Detailed feedback and suggestions",
      "Track changes for easy review",
    ],
    process: [
      { step: 1, title: "Manuscript Review", description: "Initial assessment of your manuscript's needs." },
      { step: 2, title: "Editing Plan", description: "Customized editing approach based on your goals." },
      { step: 3, title: "Deep Edit", description: "Thorough editing with detailed comments." },
      { step: 4, title: "Author Review", description: "You review changes and provide feedback." },
      { step: 5, title: "Final Polish", description: "Incorporating your feedback for the final version." },
    ],
    faqs: [
      { question: "What's the difference between editing types?", answer: "Developmental focuses on structure, line editing on prose style, and copy editing on grammar/mechanics." },
      { question: "Will you change my voice?", answer: "Never. We enhance and clarify while preserving your unique author voice." },
      { question: "How many revision rounds are included?", answer: "Our packages include 2-3 revision rounds depending on the service level." },
    ],
  },
  {
    slug: "proofreading",
    title: "Proofreading",
    shortDescription: "Catch every typo and error before your book goes to print.",
    icon: BookCheck,
    image: "/images/services/proofreading.jpg",
    heroDescription: "The final polish your manuscript needs. Our eagle-eyed proofreaders ensure your book is error-free and publication-ready.",
    features: [
      "Comprehensive error detection",
      "Grammar and punctuation correction",
      "Spelling and typo elimination",
      "Consistency checks throughout",
      "Formatting verification",
      "Final quality assurance",
    ],
    process: [
      { step: 1, title: "Document Prep", description: "Format and prepare your manuscript for review." },
      { step: 2, title: "First Pass", description: "Detailed proofreading for all errors." },
      { step: 3, title: "Quality Check", description: "Second review to ensure nothing was missed." },
      { step: 4, title: "Delivery", description: "Clean, error-free manuscript delivered." },
    ],
    faqs: [
      { question: "Is proofreading different from editing?", answer: "Yes. Proofreading is the final step focusing on surface errors, while editing addresses content and style." },
      { question: "When should I get proofreading done?", answer: "After all editing and revisions are complete, as the final step before publishing." },
    ],
  },
  {
    slug: "cover-design",
    title: "Cover Design",
    shortDescription: "Create stunning book covers that captivate readers at first glance.",
    icon: Palette,
    image: "/images/services/cover-design.jpg",
    heroDescription: "Your book cover is your first impression. Our designers create covers that not only look stunning but sell books.",
    features: [
      "Custom designs tailored to your genre",
      "Professional typography and layout",
      "Print and digital formats included",
      "Multiple concept options to choose from",
      "Unlimited revisions until perfect",
      "Source files provided upon completion",
    ],
    process: [
      { step: 1, title: "Design Brief", description: "Discuss your vision, genre, and target audience." },
      { step: 2, title: "Concept Development", description: "Create 2-3 initial design concepts." },
      { step: 3, title: "Refinement", description: "Refine your chosen concept with feedback." },
      { step: 4, title: "Finalization", description: "Prepare final files for all platforms." },
    ],
    faqs: [
      { question: "How many design concepts will I receive?", answer: "You'll receive 2-3 unique concepts to choose from, with unlimited revisions on your selected design." },
      { question: "What file formats will I get?", answer: "High-resolution files for print (PDF, TIFF) and web (JPG, PNG) optimized for all platforms." },
    ],
  },
  {
    slug: "formatting",
    title: "Book Formatting",
    shortDescription: "Professional interior layout that enhances the reading experience.",
    icon: LayoutGrid,
    image: "/images/services/formatting.jpg",
    heroDescription: "Beautiful interior design matters. We format your book for a professional, readable layout across all formats.",
    features: [
      "Print-ready interior layout",
      "eBook formatting (ePub, Mobi, KF8)",
      "Chapter headers and styling",
      "Table of contents creation",
      "Image and illustration placement",
      "Platform-specific requirements met",
    ],
    process: [
      { step: 1, title: "Format Analysis", description: "Determine requirements for your target platforms." },
      { step: 2, title: "Layout Design", description: "Create the interior design template." },
      { step: 3, title: "Content Flow", description: "Apply formatting throughout the manuscript." },
      { step: 4, title: "Quality Check", description: "Review on multiple devices and formats." },
    ],
    faqs: [
      { question: "What's included in formatting?", answer: "Page layout, chapter styling, headers/footers, table of contents, and preparation for your chosen platforms." },
      { question: "Do you format for both print and ebook?", answer: "Yes, we handle both print-ready PDFs and all major eBook formats." },
    ],
  },
  {
    slug: "publishing",
    title: "Publishing Services",
    shortDescription: "Navigate the publishing world with expert guidance and support.",
    icon: Rocket,
    image: "/images/services/publishing.jpg",
    heroDescription: "From manuscript to marketplace. We handle the complexities of publishing so you can focus on being an author.",
    features: [
      "Amazon KDP publishing and optimization",
      "IngramSpark distribution setup",
      "ISBN registration and management",
      "Metadata optimization for discoverability",
      "Pricing strategy guidance",
      "Multi-platform publishing coordination",
    ],
    process: [
      { step: 1, title: "Platform Strategy", description: "Determine the best platforms for your book." },
      { step: 2, title: "Account Setup", description: "Create and configure publishing accounts." },
      { step: 3, title: "Upload & Optimize", description: "Upload files with optimized metadata." },
      { step: 4, title: "Launch", description: "Go live and monitor initial performance." },
    ],
    faqs: [
      { question: "Which platforms do you publish to?", answer: "Amazon KDP, IngramSpark, Apple Books, Barnes & Noble, Kobo, and more." },
      { question: "Do I need my own ISBN?", answer: "We can help you obtain ISBNs or use free platform-provided ones based on your distribution goals." },
    ],
  },
  {
    slug: "book-marketing",
    title: "Book Marketing",
    shortDescription: "Reach your target readers with strategic book marketing campaigns.",
    icon: Megaphone,
    image: "/images/services/marketing.jpg",
    heroDescription: "Writing the book is just the beginning. Our marketing experts help you reach readers and build your author brand.",
    features: [
      "Amazon advertising campaigns",
      "Social media marketing strategy",
      "Book launch planning and execution",
      "Email marketing setup",
      "Author website and branding",
      "Review generation strategies",
    ],
    process: [
      { step: 1, title: "Market Research", description: "Analyze your genre, competition, and target readers." },
      { step: 2, title: "Strategy Development", description: "Create a customized marketing plan." },
      { step: 3, title: "Campaign Execution", description: "Launch and manage marketing campaigns." },
      { step: 4, title: "Optimization", description: "Monitor results and optimize for performance." },
    ],
    faqs: [
      { question: "When should I start marketing?", answer: "Ideally 2-3 months before launch to build anticipation and grow your audience." },
      { question: "Do you guarantee bestseller status?", answer: "While we can't guarantee rankings, our proven strategies maximize your book's visibility and sales potential." },
    ],
  },
  {
    slug: "audiobook-production",
    title: "Audiobook Production",
    shortDescription: "Bring your book to life with professional audiobook production.",
    icon: Headphones,
    image: "/images/services/audiobook.jpg",
    heroDescription: "Reach the growing audiobook audience. We handle everything from narration to distribution on Audible and beyond.",
    features: [
      "Professional narrator casting and selection",
      "Studio-quality recording",
      "Expert audio editing and mastering",
      "ACX and Findaway Voices distribution",
      "Retail sample creation",
      "Quality assurance to platform standards",
    ],
    process: [
      { step: 1, title: "Narrator Selection", description: "Audition and select the perfect voice for your book." },
      { step: 2, title: "Production", description: "Professional recording in acoustically treated studios." },
      { step: 3, title: "Post-Production", description: "Editing, mastering, and quality control." },
      { step: 4, title: "Distribution", description: "Upload to Audible, iTunes, and other platforms." },
    ],
    faqs: [
      { question: "Can I choose my narrator?", answer: "Absolutely! We provide auditions from multiple narrators for you to select from." },
      { question: "How long does audiobook production take?", answer: "Typically 4-8 weeks depending on book length." },
    ],
  },
  {
    slug: "book-distribution",
    title: "Book Distribution",
    shortDescription: "Get your book into stores worldwide with comprehensive distribution.",
    icon: Globe,
    image: "/images/services/distribution.jpg",
    heroDescription: "Maximize your book's reach. Our distribution network gets your book into bookstores, libraries, and online retailers globally.",
    features: [
      "Global distribution network",
      "Bookstore and library availability",
      "Online retailer presence",
      "Print-on-demand fulfillment",
      "Inventory management",
      "Sales tracking and reporting",
    ],
    process: [
      { step: 1, title: "Distribution Planning", description: "Determine your distribution goals and channels." },
      { step: 2, title: "Setup", description: "Configure distribution accounts and settings." },
      { step: 3, title: "Launch", description: "Make your book available across all channels." },
      { step: 4, title: "Management", description: "Ongoing monitoring and optimization." },
    ],
    faqs: [
      { question: "Can my book be in physical bookstores?", answer: "Yes! Through IngramSpark, your book can be ordered by bookstores and libraries worldwide." },
      { question: "What about international distribution?", answer: "Our network covers major markets in North America, Europe, Asia, and beyond." },
    ],
  },
  {
    slug: "ebook-creation",
    title: "eBook Creation",
    shortDescription: "Convert your manuscript into professional eBooks for all platforms.",
    icon: Tablet,
    image: "/images/services/ebook.jpg",
    heroDescription: "Reach digital readers everywhere. We create beautifully formatted eBooks that look perfect on every device.",
    features: [
      "ePub 3.0 creation for modern devices",
      "Kindle format optimization",
      "Responsive layout for all screen sizes",
      "Interactive table of contents",
      "Image optimization",
      "Cross-platform testing",
    ],
    process: [
      { step: 1, title: "Manuscript Prep", description: "Prepare and clean your manuscript for conversion." },
      { step: 2, title: "Conversion", description: "Convert to eBook formats with proper styling." },
      { step: 3, title: "Testing", description: "Test on multiple devices and readers." },
      { step: 4, title: "Delivery", description: "Provide final files ready for upload." },
    ],
    faqs: [
      { question: "What formats do you provide?", answer: "ePub (for Apple, Kobo, B&N), Mobi/KF8 (for Kindle), and PDF for direct sales." },
      { question: "Will images look good in the eBook?", answer: "Yes, we optimize all images for digital display while maintaining quality." },
    ],
  },
];

export const getServiceBySlug = (slug) => {
  return services.find((service) => service.slug === slug);
};

export const getAllServiceSlugs = () => {
  return services.map((service) => service.slug);
};
